const LESSON_DATA = {
  id: 17,
  title_cn: "我要多向认真的人学习",
  title_en: "I will learn from people who are careful",
  vocab: [
    { hanzi: "向", pinyin: "xiàng", pos: "prep.", meaning: "kepada; ke arah", example: "我要多向认真的人学习。" },
    { hanzi: "楼梯", pinyin: "lóutī", pos: "n.", meaning: "tangga", example: "我在楼梯那儿等你。" },
    { hanzi: "害怕", pinyin: "hàipà", pos: "v.", meaning: "takut", example: "我害怕见李老师。" },
    { hanzi: "生气", pinyin: "shēngqì", pos: "v.", meaning: "marah", example: "我怕老师生气。" },
    { hanzi: "常见", pinyin: "chángjiàn", pos: "adj.", meaning: "umum; sering terjadi", example: "做错事情是很常见的。" },
    { hanzi: "聪明", pinyin: "cōngmíng", pos: "adj.", meaning: "pintar", example: "有的人虽然很聪明,但也会出错。" },
    { hanzi: "错", pinyin: "cuò", pos: "n.", meaning: "kesalahan", example: "我把简单的事情做错了。" },
    { hanzi: "认为", pinyin: "rènwéi", pos: "v.", meaning: "menganggap; berpendapat", example: "我认为这件事不简单。" },
    { hanzi: "到处", pinyin: "dàochù", pos: "adv.", meaning: "di mana-mana", example: "同学们都在到处找工作。" },
    { hanzi: "继续", pinyin: "jìxù", pos: "v.", meaning: "melanjutkan", example: "我不想工作,还想继续学习。" },
    { hanzi: "同意", pinyin: "tóngyì", pos: "v.", meaning: "setuju", example: "我爸妈也同意我继续学习。" },
    { hanzi: "可", pinyin: "kě", pos: "conj.", meaning: "tetapi", example: "可我还没想好学什么。" },
    { hanzi: "屋子", pinyin: "wūzi", pos: "n.", meaning: "kamar; ruangan", example: "那个屋子里有些跟电脑有关的书。" },
    { hanzi: "有关", pinyin: "yǒuguān", pos: "v./prep.", meaning: "berhubungan dengan", example: "你可以去看看跟电脑有关系的书。" },
    { hanzi: "关机", pinyin: "guānjī", pos: "v.", meaning: "mematikan ponsel", example: "你的手机怎么关机了?" },
    { hanzi: "前天", pinyin: "qiántiān", pos: "n.", meaning: "kemarin lusa", example: "前天我看见家月了。" },
    { hanzi: "留学", pinyin: "liúxué", pos: "v.", meaning: "belajar di luar negeri", example: "她告诉我你打算继续留学。" },
    { hanzi: "国家", pinyin: "guójiā", pos: "n.", meaning: "negara", example: "我还没想好去哪个国家。" },
    { hanzi: "比如", pinyin: "bǐrú", pos: "v.", meaning: "misalnya", example: "比如可以去北京、上海这样的大城市。" },
    { hanzi: "查", pinyin: "chá", pos: "v.", meaning: "mencari; memeriksa", example: "好,那我上网查一查。" },
    { hanzi: "有用", pinyin: "yǒuyòng", pos: "adj.", meaning: "berguna", example: "我给你介绍几个有用的网站。" },
    { hanzi: "容易", pinyin: "róngyì", pos: "adj.", meaning: "mudah", example: "这个问题真不容易回答。" },
    { hanzi: "回答", pinyin: "huídá", pos: "v.", meaning: "menjawab", example: "我也不知道怎么回答这个问题。" },
    { hanzi: "方向", pinyin: "fāngxiàng", pos: "n.", meaning: "arah", example: "大家选择的方向都不同。" },
    { hanzi: "只有", pinyin: "zhǐyǒu", pos: "conj.", meaning: "hanya jika", example: "只有想清楚自己真正喜欢什么,才能做出最合适的选择。" },
    { hanzi: "真正", pinyin: "zhēnzhèng", pos: "adv.", meaning: "benar-benar", example: "我还不知道自己真正喜欢什么。" },
    { hanzi: "难题", pinyin: "nántí", pos: "n.", meaning: "masalah sulit", example: "想清楚真正喜欢什么是个难题。" }
  ]
};
