const LESSON_DATA = {
  id: 2,
  title_cn: "你们想吃什么就点什么",
  title_en: "You can order whatever you feel like",
  vocab: [
    { hanzi: "菜单", pinyin: "càidān", pos: "n.", meaning: "menu", example: "服务员,请给我菜单。" },
    { hanzi: "又", pinyin: "yòu", pos: "adv.", meaning: "juga (dalam pola 又...又... = sama-sama)", example: "这个西瓜又大又甜。" },
    { hanzi: "饿", pinyin: "è", pos: "adj.", meaning: "lapar", example: "我现在很饿。" },
    { hanzi: "渴", pinyin: "kě", pos: "adj.", meaning: "haus", example: "你渴不渴?我给你倒水。" },
    { hanzi: "客气", pinyin: "kèqi", pos: "v./adj.", meaning: "sungkan; sopan", example: "别客气,多吃点儿。" },
    { hanzi: "饮料", pinyin: "yǐnliào", pos: "n.", meaning: "minuman", example: "你想喝什么饮料?" },
    { hanzi: "好久", pinyin: "hǎojiǔ", pos: "adj.", meaning: "sudah lama", example: "好久不见,你好吗?" },
    { hanzi: "服务", pinyin: "fúwù", pos: "v.", meaning: "melayani", example: "这家饭馆服务得很好。" },
    { hanzi: "员", pinyin: "yuán", pos: "suf.", meaning: "akhiran penunjuk profesi/orang", example: "我姐姐是一名服务员。" },
    { hanzi: "双", pinyin: "shuāng", pos: "m.", meaning: "pasang", example: "我想买一双鞋。" },
    { hanzi: "筷子", pinyin: "kuàizi", pos: "n.", meaning: "sumpit", example: "请给我一双筷子。" },
    { hanzi: "勺子", pinyin: "sháozi", pos: "n.", meaning: "sendok", example: "吃饭的时候我喜欢用勺子。" },
    { hanzi: "碗", pinyin: "wǎn", pos: "n.", meaning: "mangkuk", example: "桌子上有一个碗。" },
    { hanzi: "马上", pinyin: "mǎshàng", pos: "adv.", meaning: "segera", example: "我马上就到。" },
    { hanzi: "热情", pinyin: "rèqíng", pos: "adj.", meaning: "ramah; penuh semangat", example: "那儿的服务员很热情。" },
    { hanzi: "尝", pinyin: "cháng", pos: "v.", meaning: "mencicipi", example: "你尝尝这个菜怎么样。" },
    { hanzi: "记", pinyin: "jì", pos: "v.", meaning: "mengingat", example: "我记不住他的名字。" },
    { hanzi: "用", pinyin: "yòng", pos: "v.", meaning: "makan/minum; menggunakan", example: "请慢用。" },
    { hanzi: "鸡", pinyin: "jī", pos: "n.", meaning: "ayam", example: "我想吃鸡肉饭。" },
    { hanzi: "张", pinyin: "zhāng", pos: "m.", meaning: "(kata bantu bilangan untuk benda pipih)", example: "桌子上有一张纸。" },
    { hanzi: "不用", pinyin: "búyòng", pos: "adv.", meaning: "tidak perlu", example: "不用谢。" },
    { hanzi: "选", pinyin: "xuǎn", pos: "v.", meaning: "memilih", example: "你想选哪个?" },
    { hanzi: "外卖", pinyin: "wàimài", pos: "n./v.", meaning: "makanan antar; layanan pesan-antar", example: "今天晚上我们点外卖吧。" },
    { hanzi: "方便", pinyin: "fāngbiàn", pos: "adj.", meaning: "praktis; nyaman", example: "手机付钱很方便。" },
    { hanzi: "蛋糕", pinyin: "dàngāo", pos: "n.", meaning: "kue", example: "这个蛋糕是我做的。" },
    { hanzi: "只", pinyin: "zhǐ", pos: "adv.", meaning: "hanya", example: "我只喝水,不喝饮料。" },
    { hanzi: "方便面", pinyin: "fāngbiànmiàn", pos: "n.", meaning: "mi instan", example: "我今天中午吃方便面。" },
    { hanzi: "简单", pinyin: "jiǎndān", pos: "adj.", meaning: "sederhana", example: "这个问题很简单。" }
  ]
};
