const LESSON_DATA = {
  id: 1,
  title_cn: "我们去机场接你们",
  title_en: "We will pick you up at the airport",
  vocab: [
    { hanzi: "以为", pinyin: "yǐwéi", pos: "v.", meaning: "mengira; menganggap (biasanya keliru)", example: "我以为你今天不来了。" },
    { hanzi: "像", pinyin: "xiàng", pos: "v.", meaning: "mirip; menyerupai", example: "她长得很像她妈妈。" },
    { hanzi: "长", pinyin: "zhǎng", pos: "v.", meaning: "tumbuh; berkembang", example: "这孩子长得很快。" },
    { hanzi: "身高", pinyin: "shēngāo", pos: "n.", meaning: "tinggi badan", example: "他的身高是一米八。" },
    { hanzi: "米", pinyin: "mǐ", pos: "m.", meaning: "meter", example: "这条河有十米宽。" },
    { hanzi: "瘦", pinyin: "shòu", pos: "adj.", meaning: "kurus", example: "他最近瘦了很多。" },
    { hanzi: "接", pinyin: "jiē", pos: "v.", meaning: "menjemput", example: "明天我去机场接你。" },
    { hanzi: "行李", pinyin: "xíngli", pos: "n.", meaning: "bagasi; barang bawaan", example: "我的行李很重。" },
    { hanzi: "丢", pinyin: "diū", pos: "v.", meaning: "kehilangan; menghilangkan", example: "他把手机丢了。" },
    { hanzi: "箱子", pinyin: "xiāngzi", pos: "n.", meaning: "koper; kotak", example: "这个箱子是我的。" },
    { hanzi: "号码", pinyin: "hàomǎ", pos: "n.", meaning: "nomor", example: "你的电话号码是多少?" },
    { hanzi: "好像", pinyin: "hǎoxiàng", pos: "adv.", meaning: "sepertinya", example: "外面好像下雨了。" },
    { hanzi: "重要", pinyin: "zhòngyào", pos: "adj.", meaning: "penting", example: "这件事对我很重要。" },
    { hanzi: "着急", pinyin: "zháojí", pos: "adj.", meaning: "cemas; khawatir", example: "别着急,慢慢说。" },
    { hanzi: "护照", pinyin: "hùzhào", pos: "n.", meaning: "paspor", example: "出国旅游需要护照。" },
    { hanzi: "服务台", pinyin: "fúwùtái", pos: "n.", meaning: "meja layanan; resepsionis", example: "你可以去服务台问问。" },
    { hanzi: "应该", pinyin: "yīnggāi", pos: "mod.", meaning: "seharusnya", example: "你应该多喝水。" },
    { hanzi: "站", pinyin: "zhàn", pos: "v.", meaning: "berdiri", example: "请大家站起来。" },
    { hanzi: "中间", pinyin: "zhōngjiān", pos: "n.", meaning: "tengah", example: "我坐在他们中间。" },
    { hanzi: "短", pinyin: "duǎn", pos: "adj.", meaning: "pendek", example: "这条裤子太短了。" },
    { hanzi: "头发", pinyin: "tóufa", pos: "n.", meaning: "rambut", example: "她的头发很长。" },
    { hanzi: "年轻", pinyin: "niánqīng", pos: "adj.", meaning: "muda", example: "那个老师很年轻。" },
    { hanzi: "发现", pinyin: "fāxiàn", pos: "v.", meaning: "menemukan; menyadari", example: "我发现他不在家。" },
    { hanzi: "不见", pinyin: "bújiàn", pos: "v.", meaning: "hilang; tidak ada", example: "我的钥匙不见了。" },
    { hanzi: "带", pinyin: "dài", pos: "v.", meaning: "membawa", example: "明天请带你的护照来。" },
    { hanzi: "帮助", pinyin: "bāngzhù", pos: "v.", meaning: "membantu", example: "谢谢你帮助我。" },
    { hanzi: "照片", pinyin: "zhàopiàn", pos: "n.", meaning: "foto", example: "这张照片很好看。" }
  ]
};
