const LESSON_DATA = {
  id: 10,
  title_cn: "你明天再把书还给我",
  title_en: "You can return the book to me tomorrow",
  vocab: [
    { hanzi: "数学", pinyin: "shùxué", pos: "n.", meaning: "matematika", example: "我的数学成绩不太好。" },
    { hanzi: "认真", pinyin: "rènzhēn", pos: "adj.", meaning: "sungguh-sungguh; teliti", example: "他上课很认真。" },
    { hanzi: "笔记", pinyin: "bǐjì", pos: "n.", meaning: "catatan", example: "请借我看看你的笔记。" },
    { hanzi: "清楚", pinyin: "qīngchu", pos: "adj./v.", meaning: "jelas; mengetahui dengan jelas", example: "老师讲得很清楚。" },
    { hanzi: "黑板", pinyin: "hēibǎn", pos: "n.", meaning: "papan tulis", example: "老师把生词写在黑板上。" },
    { hanzi: "把", pinyin: "bǎ", pos: "prep.", meaning: "(kata depan untuk memindahkan objek sebelum kata kerja)", example: "请把书还给我。" },
    { hanzi: "作业", pinyin: "zuòyè", pos: "n.", meaning: "pekerjaan rumah", example: "我每天都要写作业。" },
    { hanzi: "遍", pinyin: "biàn", pos: "m.", meaning: "kali (dari awal sampai akhir)", example: "这本书我看了三遍。" },
    { hanzi: "提高", pinyin: "tígāo", pos: "v.", meaning: "meningkatkan", example: "多练习可以提高汉语水平。" },
    { hanzi: "历史", pinyin: "lìshǐ", pos: "n.", meaning: "sejarah", example: "他对中国历史很感兴趣。" },
    { hanzi: "难", pinyin: "nán", pos: "adj.", meaning: "sulit", example: "这个问题有点儿难。" },
    { hanzi: "要求", pinyin: "yāoqiú", pos: "n./v.", meaning: "persyaratan; mensyaratkan", example: "老师对我们的要求很高。" },
    { hanzi: "差", pinyin: "chà", pos: "adj./v.", meaning: "buruk; kurang", example: "他这次考得有点儿差。" },
    { hanzi: "复习", pinyin: "fùxí", pos: "v.", meaning: "mengulas pelajaran", example: "考试以前要好好复习。" },
    { hanzi: "外语", pinyin: "wàiyǔ", pos: "n.", meaning: "bahasa asing", example: "他会说三种外语。" },
    { hanzi: "当然", pinyin: "dāngrán", pos: "adv.", meaning: "tentu saja", example: "你可以问我,当然可以。" },
    { hanzi: "遇到", pinyin: "yùdào", pos: "v.", meaning: "menemui; bertemu (masalah)", example: "学习中遇到问题很正常。" },
    { hanzi: "办公室", pinyin: "bàngōngshì", pos: "n.", meaning: "kantor", example: "老师现在在办公室。" },
    { hanzi: "页", pinyin: "yè", pos: "m.", meaning: "halaman", example: "请打开第十页。" },
    { hanzi: "对话", pinyin: "duìhuà", pos: "v.", meaning: "berdialog", example: "我们两个人对话吧。" },
    { hanzi: "明白", pinyin: "míngbai", pos: "v./adj.", meaning: "mengerti; jelas", example: "老师讲了以后,我明白了。" },
    { hanzi: "讲", pinyin: "jiǎng", pos: "v.", meaning: "menjelaskan", example: "老师又给我们讲了一遍。" },
    { hanzi: "句", pinyin: "jù", pos: "m.", meaning: "(kata bantu untuk kalimat)", example: "他说了几句话就走了。" },
    { hanzi: "句子", pinyin: "jùzi", pos: "n.", meaning: "kalimat", example: "这个句子我不太明白。" },
    { hanzi: "年级", pinyin: "niánjí", pos: "n.", meaning: "tingkat kelas", example: "我妹妹上小学三年级。" },
    { hanzi: "后年", pinyin: "hòunián", pos: "n.", meaning: "tahun depan lusa", example: "后年我就要上高中了。" },
    { hanzi: "一般", pinyin: "yìbān", pos: "adj.", meaning: "umumnya; biasa", example: "中国的学校一般是小学六年。" },
    { hanzi: "努力", pinyin: "nǔlì", pos: "adj./v.", meaning: "bersungguh-sungguh; berusaha keras", example: "为了考上好高中,他非常努力。" }
  ]
};
