const LESSON_DATA = {
  id: 5,
  title_cn: "这样的照片才好看",
  title_en: "Photos like these are the best",
  vocab: [
    { hanzi: "总是", pinyin: "zǒngshì", pos: "adv.", meaning: "selalu", example: "他总是第一个到教室。" },
    { hanzi: "终于", pinyin: "zhōngyú", pos: "adv.", meaning: "akhirnya", example: "我终于做完作业了。" },
    { hanzi: "爬", pinyin: "pá", pos: "v.", meaning: "mendaki; memanjat", example: "周末我们去爬山吧。" },
    { hanzi: "山", pinyin: "shān", pos: "n.", meaning: "gunung; bukit", example: "这座山不太高。" },
    { hanzi: "锻炼", pinyin: "duànliàn", pos: "v.", meaning: "berolahraga", example: "我每天早上锻炼身体。" },
    { hanzi: "照", pinyin: "zhào", pos: "v.", meaning: "memotret", example: "请帮我照一张照片。" },
    { hanzi: "鞋", pinyin: "xié", pos: "n.", meaning: "sepatu", example: "这双鞋很好看。" },
    { hanzi: "大衣", pinyin: "dàyī", pos: "n.", meaning: "mantel", example: "外面冷,穿上大衣吧。" },
    { hanzi: "拍照", pinyin: "pāizhào", pos: "v.", meaning: "memotret; berfoto", example: "我们在公园拍照吧。" },
    { hanzi: "感兴趣", pinyin: "gǎn xìngqù", pos: "v.phr.", meaning: "tertarik pada", example: "我对中国音乐很感兴趣。" },
    { hanzi: "照相", pinyin: "zhàoxiàng", pos: "v.", meaning: "memotret; berfoto", example: "她喜欢在山上照相。" },
    { hanzi: "难看", pinyin: "nánkàn", pos: "adj.", meaning: "jelek; tidak enak dipandang", example: "这张照片有点儿难看。" },
    { hanzi: "比较", pinyin: "bǐjiào", pos: "v./adv.", meaning: "membandingkan; relatif", example: "这两张照片比较一下就知道了。" },
    { hanzi: "水平", pinyin: "shuǐpíng", pos: "n.", meaning: "level; taraf kemampuan", example: "他的汉语水平很高。" },
    { hanzi: "太阳", pinyin: "tàiyáng", pos: "n.", meaning: "matahari", example: "今天的太阳很大。" },
    { hanzi: "树", pinyin: "shù", pos: "n.", meaning: "pohon", example: "公园里有很多树。" },
    { hanzi: "干", pinyin: "gàn", pos: "v.", meaning: "melakukan; mengerjakan", example: "你周末想干什么?" },
    { hanzi: "电", pinyin: "diàn", pos: "n.", meaning: "listrik", example: "我的手机没电了。" },
    { hanzi: "收到", pinyin: "shōudào", pos: "v.", meaning: "menerima", example: "我收到了你的邮件。" },
    { hanzi: "封", pinyin: "fēng", pos: "m.", meaning: "(kata bantu bilangan untuk surat/email)", example: "我给她写了一封信。" },
    { hanzi: "邮件", pinyin: "yóujiàn", pos: "n.", meaning: "email; surat", example: "请检查一下你的邮件。" },
    { hanzi: "难过", pinyin: "nánguò", pos: "adj.", meaning: "sedih", example: "听到这个消息,她很难过。" },
    { hanzi: "哈哈", pinyin: "hāhā", pos: "int.", meaning: "haha (tawa)", example: "哈哈,这个笑话真有意思。" },
    { hanzi: "音乐", pinyin: "yīnyuè", pos: "n.", meaning: "musik", example: "我喜欢听音乐。" },
    { hanzi: "兴趣", pinyin: "xìngqù", pos: "n.", meaning: "minat", example: "他对足球很有兴趣。" },
    { hanzi: "会", pinyin: "huì", pos: "n.", meaning: "acara; pertemuan", example: "明天晚上有一个音乐会。" },
    { hanzi: "结束", pinyin: "jiéshù", pos: "v.", meaning: "selesai; berakhir", example: "电影八点结束。" }
  ]
};
