const LESSON_DATA = {
  id: 11,
  title_cn: "看来我没办法解决这个问题",
  title_en: "It seems I can't solve this problem",
  vocab: [
    { hanzi: "会议", pinyin: "huìyì", pos: "n.", meaning: "rapat", example: "会议下午三点开始。" },
    { hanzi: "经理", pinyin: "jīnglǐ", pos: "n.", meaning: "manajer", example: "经理今天不在办公室。" },
    { hanzi: "开会", pinyin: "kāihuì", pos: "v.", meaning: "mengadakan rapat", example: "我们明天上午开会。" },
    { hanzi: "后天", pinyin: "hòutiān", pos: "n.", meaning: "lusa", example: "后天是我的生日。" },
    { hanzi: "地点", pinyin: "dìdiǎn", pos: "n.", meaning: "lokasi", example: "会议地点换到第一会议室了。" },
    { hanzi: "室", pinyin: "shì", pos: "n.", meaning: "ruangan", example: "他在会议室等我们。" },
    { hanzi: "发", pinyin: "fā", pos: "v.", meaning: "mengirim", example: "请把这个文件发给我。" },
    { hanzi: "笔记本电脑", pinyin: "bǐjìběn diànnǎo", pos: "n.", meaning: "laptop", example: "我的笔记本电脑坏了。" },
    { hanzi: "或者", pinyin: "huòzhě", pos: "conj.", meaning: "atau", example: "你可以用手机或者电脑。" },
    { hanzi: "声音", pinyin: "shēngyīn", pos: "n.", meaning: "suara", example: "我听不清楚你的声音。" },
    { hanzi: "看来", pinyin: "kànlái", pos: "v.", meaning: "tampaknya", example: "看来今天开不了会了。" },
    { hanzi: "办法", pinyin: "bànfǎ", pos: "n.", meaning: "cara; solusi", example: "这个问题一定有办法解决。" },
    { hanzi: "解决", pinyin: "jiějué", pos: "v.", meaning: "menyelesaikan", example: "我们得想办法解决这个问题。" },
    { hanzi: "只能", pinyin: "zhǐ néng", pos: "adv.", meaning: "hanya bisa", example: "电梯坏了,我们只能走楼梯。" },
    { hanzi: "别人", pinyin: "biérén", pos: "pron.", meaning: "orang lain", example: "这件事我得问问别人。" },
    { hanzi: "请假", pinyin: "qǐngjià", pos: "v.", meaning: "izin cuti", example: "他今天请假了,没来上班。" },
    { hanzi: "同事", pinyin: "tóngshì", pos: "n.", meaning: "rekan kerja", example: "我的同事都很热情。" },
    { hanzi: "休假", pinyin: "xiūjià", pos: "v.", meaning: "berlibur; cuti", example: "下周我要去休假。" },
    { hanzi: "怕", pinyin: "pà", pos: "v.", meaning: "takut; khawatir", example: "我怕这些工作做不完。" },
    { hanzi: "邮箱", pinyin: "yóuxiāng", pos: "n.", meaning: "kotak surel", example: "请把文件发到我的邮箱里。" },
    { hanzi: "愿意", pinyin: "yuànyì", pos: "mod.", meaning: "bersedia", example: "你愿意去上海工作吗?" },
    { hanzi: "城市", pinyin: "chéngshì", pos: "n.", meaning: "kota", example: "北京是一个很大的城市。" },
    { hanzi: "离开", pinyin: "líkāi", pos: "v.", meaning: "meninggalkan", example: "他明年要离开这个城市。" },
    { hanzi: "机会", pinyin: "jīhuì", pos: "n.", meaning: "kesempatan", example: "去上海工作会有更好的机会。" },
    { hanzi: "生活", pinyin: "shēnghuó", pos: "n./v.", meaning: "kehidupan; hidup", example: "对我来说,生活比工作更重要。" },
    { hanzi: "为", pinyin: "wèi", pos: "prep.", meaning: "demi; untuk", example: "我不愿意为工作离开家人。" },
    { hanzi: "或", pinyin: "huò", pos: "conj.", meaning: "atau", example: "你可以坐公交车或地铁去。" }
  ]
};
