const LESSON_DATA = {
  id: 8,
  title_cn: "今天我出院了",
  title_en: "Today I was discharged from the hospital",
  vocab: [
    { hanzi: "最近", pinyin: "zuìjìn", pos: "n.", meaning: "belakangan ini; akhir-akhir ini", example: "你最近怎么样?" },
    { hanzi: "常", pinyin: "cháng", pos: "adv.", meaning: "sering", example: "他常去体育馆运动。" },
    { hanzi: "体育馆", pinyin: "tǐyùguǎn", pos: "n.", meaning: "gedung olahraga", example: "我们在体育馆打篮球。" },
    { hanzi: "习惯", pinyin: "xíguàn", pos: "n./v.", meaning: "kebiasaan; terbiasa", example: "早起是个好习惯。" },
    { hanzi: "胖", pinyin: "pàng", pos: "adj.", meaning: "gemuk", example: "他今年胖了很多。" },
    { hanzi: "健康", pinyin: "jiànkāng", pos: "adj.", meaning: "sehat", example: "多运动对健康很好。" },
    { hanzi: "以后", pinyin: "yǐhòu", pos: "n.", meaning: "setelah; nanti", example: "下课以后我们去吃饭吧。" },
    { hanzi: "羽毛球", pinyin: "yǔmáoqiú", pos: "n.", meaning: "bulu tangkis", example: "我周末喜欢打羽毛球。" },
    { hanzi: "耳朵", pinyin: "ěrduo", pos: "n.", meaning: "telinga", example: "他的耳朵有点儿疼。" },
    { hanzi: "感冒", pinyin: "gǎnmào", pos: "v./n.", meaning: "masuk angin; flu", example: "我昨天感冒了。" },
    { hanzi: "发烧", pinyin: "fāshāo", pos: "v.", meaning: "demam", example: "他今天发烧了,没去上课。" },
    { hanzi: "低", pinyin: "dī", pos: "adj.", meaning: "rendah", example: "现在温度有点儿低。" },
    { hanzi: "关心", pinyin: "guānxīn", pos: "v.", meaning: "peduli; memperhatikan", example: "谢谢你关心我。" },
    { hanzi: "注意", pinyin: "zhùyì", pos: "v.", meaning: "memperhatikan; waspada", example: "过马路的时候要注意安全。" },
    { hanzi: "突然", pinyin: "tūrán", pos: "adj.", meaning: "tiba-tiba", example: "外面突然下起了大雨。" },
    { hanzi: "住院", pinyin: "zhùyuàn", pos: "v.", meaning: "dirawat di rumah sakit", example: "他生病了,现在正在住院。" },
    { hanzi: "担心", pinyin: "dānxīn", pos: "v.", meaning: "khawatir", example: "别担心,我没事。" },
    { hanzi: "腿", pinyin: "tuǐ", pos: "n.", meaning: "kaki (tungkai)", example: "他的腿疼了好几天了。" },
    { hanzi: "病人", pinyin: "bìngrén", pos: "n.", meaning: "pasien", example: "医院里有很多病人。" },
    { hanzi: "差不多", pinyin: "chàbuduō", pos: "adv./adj.", meaning: "hampir; kurang lebih", example: "我们差不多到了。" },
    { hanzi: "得", pinyin: "děi", pos: "mod.", meaning: "harus", example: "你得多休息。" },
    { hanzi: "开心", pinyin: "kāixīn", pos: "adj.", meaning: "senang", example: "看到朋友们,我很开心。" },
    { hanzi: "出院", pinyin: "chūyuàn", pos: "v.", meaning: "keluar dari rumah sakit", example: "医生说他明天可以出院了。" },
    { hanzi: "开", pinyin: "kāi", pos: "v.", meaning: "meresepkan (obat)", example: "医生给我开了一些药。" },
    { hanzi: "种", pinyin: "zhǒng", pos: "m.", meaning: "jenis; macam", example: "这种药一天吃三次。" },
    { hanzi: "方法", pinyin: "fāngfǎ", pos: "n.", meaning: "cara; metode", example: "医生告诉了我吃药的方法。" },
    { hanzi: "其他", pinyin: "qítā", pos: "pron.", meaning: "lainnya", example: "除了这个,其他的都可以。" },
    { hanzi: "心里", pinyin: "xīnlǐ", pos: "n.", meaning: "dalam hati; pikiran", example: "他说的话我都记在心里了。" }
  ]
};
