const LESSON_DATA = {
  id: 4,
  title_cn: "这家宾馆跟别的都不一样",
  title_en: "This hotel is unlike any other",
  vocab: [
    { hanzi: "假期", pinyin: "jiàqī", pos: "n.", meaning: "liburan", example: "这个假期我想去旅游。" },
    { hanzi: "海", pinyin: "hǎi", pos: "n.", meaning: "laut", example: "我喜欢在海边散步。" },
    { hanzi: "草原", pinyin: "cǎoyuán", pos: "n.", meaning: "padang rumput", example: "草原上的风景很美。" },
    { hanzi: "主意", pinyin: "zhǔyi", pos: "n.", meaning: "ide; gagasan", example: "这是个好主意。" },
    { hanzi: "骑", pinyin: "qí", pos: "v.", meaning: "menaiki (sepeda/kuda dsb.)", example: "我每天骑自行车上班。" },
    { hanzi: "马", pinyin: "mǎ", pos: "n.", meaning: "kuda", example: "那匹马跑得很快。" },
    { hanzi: "羊", pinyin: "yáng", pos: "n.", meaning: "domba; kambing", example: "农场里有几只羊。" },
    { hanzi: "月亮", pinyin: "yuèliang", pos: "n.", meaning: "bulan", example: "今晚的月亮很亮。" },
    { hanzi: "一定", pinyin: "yídìng", pos: "adv.", meaning: "pasti", example: "我明天一定去看你。" },
    { hanzi: "刻", pinyin: "kè", pos: "m.", meaning: "seperempat jam", example: "现在是三点一刻。" },
    { hanzi: "起飞", pinyin: "qǐfēi", pos: "v.", meaning: "lepas landas", example: "飞机十点起飞。" },
    { hanzi: "宾馆", pinyin: "bīnguǎn", pos: "n.", meaning: "hotel", example: "我们住在一家宾馆。" },
    { hanzi: "特别", pinyin: "tèbié", pos: "adj./adv.", meaning: "istimewa; khusus", example: "这个地方很特别。" },
    { hanzi: "别的", pinyin: "biéde", pos: "pron.", meaning: "yang lain", example: "我不要这个,我要别的。" },
    { hanzi: "一样", pinyin: "yíyàng", pos: "adj.", meaning: "sama", example: "他的想法跟我一样。" },
    { hanzi: "牛", pinyin: "niú", pos: "n.", meaning: "sapi", example: "农村里养了很多牛。" },
    { hanzi: "相机", pinyin: "xiàngjī", pos: "n.", meaning: "kamera", example: "别忘了带相机。" },
    { hanzi: "欢迎", pinyin: "huānyíng", pos: "v.", meaning: "menyambut; selamat datang", example: "欢迎你来我家玩。" },
    { hanzi: "司机", pinyin: "sījī", pos: "n.", meaning: "sopir", example: "他是公司的司机。" },
    { hanzi: "晚点", pinyin: "wǎndiǎn", pos: "v.", meaning: "terlambat (pesawat/kereta dsb.)", example: "我的航班晚点了。" },
    { hanzi: "久", pinyin: "jiǔ", pos: "adj.", meaning: "lama", example: "我们好久没见了。" },
    { hanzi: "除了", pinyin: "chúle", pos: "prep.", meaning: "selain", example: "除了我,大家都去了。" },
    { hanzi: "以外", pinyin: "yǐwài", pos: "n.", meaning: "selain itu; kecuali", example: "除了中文以外,我还会说英语。" },
    { hanzi: "先", pinyin: "xiān", pos: "adv.", meaning: "duluan; lebih dulu", example: "你先走吧,我马上就到。" },
    { hanzi: "一直", pinyin: "yìzhí", pos: "adv.", meaning: "terus-menerus; selalu", example: "他一直在等你。" },
    { hanzi: "干净", pinyin: "gānjìng", pos: "adj.", meaning: "bersih", example: "房间很干净。" },
    { hanzi: "满意", pinyin: "mǎnyì", pos: "v.", meaning: "puas", example: "我对这个结果很满意。" }
  ]
};
